schulzcodes_oauth_server_auth_login:
    path:     /oauth/v2/auth_login
    defaults: { _controller: UserBundle:Security:login }
fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

